In [1]:
import pandas as pd

In [2]:
android_vk = pd.read_excel('C:/Users/Admin/Desktop/Devs/anal/Game dev/task2/android_vk.xlsx')
direct_ok = pd.read_excel('C:/Users/Admin/Desktop/Devs/anal/Game dev/task2/direct_ok.xlsx')

In [3]:
android_vk.head(5)

,ID игрока,Платформа,Туториал: Начало,Туториал: 1,Туториал: 2,Туториал: 3,Туториал: 4,Туториал: 5
0,46837070,Android VK,0.0,1.0,2.0,3.0,4.0,5.0
1,46837225,Android VK,0.0,1.0,2.0,3.0,4.0,5.0
2,46837417,Android VK,0.0,1.0,2.0,3.0,4.0,5.0
3,46837576,Android VK,0.0,1.0,2.0,3.0,4.0,5.0
4,46837877,Android VK,0.0,1.0,2.0,3.0,4.0,5.0

In [4]:
direct_ok.head(5)

,ID игрока,Платформа,Туториал: Начало,Туториал: 1,Туториал: 2,Туториал: 3,Туториал: 4,Туториал: 5
0,46409470,Direct OK,0.0,NaN,NaN,NaN,NaN,NaN
1,46409474,Direct OK,0.0,1.0,2.0,3.0,4.0,NaN
2,46410059,Direct OK,0.0,1.0,2.0,3.0,4.0,5.0
3,46410215,Direct OK,0.0,NaN,NaN,NaN,NaN,NaN
4,46410497,Direct OK,0.0,NaN,NaN,NaN,NaN,NaN

In [5]:
android_vk.columns

Index(['ID игрока', 'Платформа', 'Туториал: Начало', 'Туториал:  1',
       'Туториал:  2', 'Туториал:  3', 'Туториал:  4', 'Туториал:  5'],
      dtype='object')

In [6]:
android_vk = android_vk.rename(columns={'ID игрока': 'gamer_id', 'Платформа': 'platform', 'Туториал: Начало': 'tutorial0', 'Туториал:  1': 'tutorial1', 'Туториал:  2': 'tutorial2', 'Туториал:  3': 'tutorial3','Туториал:  4': 'tutorial4', 'Туториал:  5': 'tutorial5'})

In [7]:
direct_ok = direct_ok.rename(columns={'ID игрока': 'gamer_id', 'Платформа': 'platform', 'Туториал: Начало': 'tutorial0', 'Туториал:  1': 'tutorial1', 'Туториал:  2': 'tutorial2', 'Туториал:  3': 'tutorial3','Туториал:  4': 'tutorial4', 'Туториал:  5': 'tutorial5'})

In [8]:
#функция, выводит на экран размер таблицы, количество уникальный и пропущенных значений для каждого столбца
def preliminary_analysis (df):
    #print(f'{df.head(3)}\n')
    print(f'Размер таблицы {df.shape}\n')
    print(f'''Уникальные значения 
{df.nunique().to_string()}\n''')
    if (len(df.isna().sum().loc[lambda x : x > 0]) > 0):
        print(f'''Пропущенные значения 
{df.isna().sum().loc[lambda x : x > 0].to_string()}\n''')
    else:
        print(f'''Пропущенные значения 
отсутствуют\n''')
        print(f'''Типы данных 
{df.dtypes.to_string()}\n''')

In [9]:
preliminary_analysis(android_vk)

Размер таблицы (998, 8)

Уникальные значения
gamer_id     998
platform       1
tutorial0      1
tutorial1      1
tutorial2      1
tutorial3      1
tutorial4      1
tutorial5      1

Пропущенные значения
tutorial0     3
tutorial1    30
tutorial2    41
tutorial3    43
tutorial4    59
tutorial5    70

In [10]:
preliminary_analysis(direct_ok)

Размер таблицы (1992, 8)

Уникальные значения
gamer_id     1992
platform        1
tutorial0       1
tutorial1       1
tutorial2       1
tutorial3       1
tutorial4       1
tutorial5       1

Пропущенные значения
tutorial0     119
tutorial1     663
tutorial2     793
tutorial3     813
tutorial4     909
tutorial5    1003

In [11]:
android_vk.shape

(998, 8)

In [12]:
direct_ok.shape

(1992, 8)

In [13]:
android_vk.dtypes

gamer_id       int64
platform      object
tutorial0    float64
tutorial1    float64
tutorial2    float64
tutorial3    float64
tutorial4    float64
tutorial5    float64
dtype: object

In [14]:
direct_ok.dtypes

gamer_id       int64
platform      object
tutorial0    float64
tutorial1    float64
tutorial2    float64
tutorial3    float64
tutorial4    float64
tutorial5    float64
dtype: object

In [57]:
android_vk2 = android_vk.notnull().astype('int')

In [58]:
android_vk2['gamer_id'] = android_vk['gamer_id']
android_vk2['platform'] = android_vk['platform']

In [59]:
android_vk2

,gamer_id,platform,tutorial0,tutorial1,tutorial2,tutorial3,tutorial4,tutorial5
0,46837070,Android VK,1,1,1,1,1,1
1,46837225,Android VK,1,1,1,1,1,1
2,46837417,Android VK,1,1,1,1,1,1
3,46837576,Android VK,1,1,1,1,1,1
4,46837877,Android VK,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...
993,47235093,Android VK,1,1,1,1,1,1
994,47235439,Android VK,1,1,1,1,1,1
995,47235551,Android VK,1,1,1,1,1,1
996,47235570,Android VK,1,1,1,1,1,1
997,47235575,Android VK,1,1,1,1,1,1

In [63]:
android_vk2['crush_step'] = android_vk2.tutorial0 + android_vk2.tutorial1 +android_vk2.tutorial2 + android_vk2.tutorial3 + android_vk2.tutorial4 + android_vk2.tutorial5

In [64]:
android_vk2

,gamer_id,platform,tutorial0,tutorial1,tutorial2,tutorial3,tutorial4,tutorial5,crush_step
0,46837070,Android VK,1,1,1,1,1,1,6
1,46837225,Android VK,1,1,1,1,1,1,6
2,46837417,Android VK,1,1,1,1,1,1,6
3,46837576,Android VK,1,1,1,1,1,1,6
4,46837877,Android VK,1,1,1,1,1,1,6
...,...,...,...,...,...,...,...,...,...
993,47235093,Android VK,1,1,1,1,1,1,6
994,47235439,Android VK,1,1,1,1,1,1,6
995,47235551,Android VK,1,1,1,1,1,1,6
996,47235570,Android VK,1,1,1,1,1,1,6
997,47235575,Android VK,1,1,1,1,1,1,6

In [20]:
android_crush = android_vk2\
    .query('crush_step < 6')\
    .groupby('crush_step', as_index=False)\
    .agg({'platform': 'count'})\
    .rename(columns = {'platform': 'count_crush'})
android_crush

   crush_step  count_crush
0           0            3
1           1           27
2           2           11
3           3            2
4           4           16
5           5           11

In [50]:
percent = android_crush.count_crush.to_list()
percent.insert(0, android_vk.shape[0])
percent.append(0)
percent

[998, 3, 27, 11, 2, 16, 11, 0]

In [51]:
a = 0
per = []
for i in percent:
    s=percent[a]-percent[a+1]
    a = a + 1

IndexError: list index out of range

In [52]:
a

7

In [41]:
per

[987, -995, 24, -16, -9, 14, -5]

In [82]:
start = android_vk2.shape[0]

In [86]:
android_vk2[['tutorial0', 'tutorial1', 'tutorial2', 'tutorial3', 'tutorial4', 'tutorial5']]

     tutorial0  tutorial1  tutorial2  tutorial3  tutorial4  tutorial5
0            1          1          1          1          1          1
1            1          1          1          1          1          1
2            1          1          1          1          1          1
3            1          1          1          1          1          1
4            1          1          1          1          1          1
..         ...        ...        ...        ...        ...        ...
993          1          1          1          1          1          1
994          1          1          1          1          1          1
995          1          1          1          1          1          1
996          1          1          1          1          1          1
997          1          1          1          1          1          1

[998 rows x 6 columns]

In [99]:
list_cr =  android_vk2[['tutorial0', 'tutorial1', 'tutorial2', 'tutorial3', 'tutorial4', 'tutorial5']].sum().to_list()
#list_cr.insert(0, android_vk.shape[0])
#list_cr.pop()

In [100]:
list_cr

[995, 968, 957, 955, 939, 928]

In [101]:
android_crush['user_crush'] = list_cr

In [102]:
android_crush

   crush_step  count_crush  user_crush
0           0            3         995
1           1           27         968
2           2           11         957
3           3            2         955
4           4           16         939
5           5           11         928